### ISSUE TITLE
Restore tab option auto-closes gedit if no tabs were left open the last time you quit

### ISSUE THREAD

**Issue by thebunnyrules** [jefferyto/gedit-ex-mortis#1]
Hi, if I have tabs that are opened when I quit gedit, this extension works well but if I close all my tabs, the next time I try to open gedit, ex-mortis will just re-close (effectively locking me out of the app).

PS - great extension BTW. brings some really need functionality to this editor.

**Comment by jefferyto** [comment]
Thanks for the kind words :smile: And thanks for this report; I'm a little embarrassed I didn't test this case earlier. Will push a new version with a fix very soon.

**Comment by thebunnyrules** [comment]
Thanks so much! :) I appreciate it.
