### ISSUE TITLE
Relicense with GPLv2+

### ISSUE THREAD

**Issue by jefferyto** [jefferyto/gedit-ex-mortis#13]
This plugin is currently licensed under GPLv3+. To be 100% compatible with gedit, I'd like to change the license to GPLv2+.

@Habetdin: would you agree to have your contribution relicensed under GPLv2+?

**Comment by Habetdin** [comment]
@jefferyto yes, sure.

I also will update the translation later.

**Comment by jefferyto** [comment]
Thanks @Habetdin!

> I also will update the translation later.

The new strings are all from the settings schema; I don't think they are visible to the user (to be honest I'm not entirely sure they should be included in the .pot file) so I'm not sure there is a big need yet for them to be translated.
