### ISSUE TITLE
ex-mortis resulting in weird window behavior when session restore is enabled

### ISSUE THREAD

**Issue by thebunnyrules** [jefferyto/gedit-ex-mortis#4]
Hello Jeffry,

I've been using your awesome extension for a while on gedit 3.26 (ubuntu 17.10). I've just recently updated to gedit 3.30 (18.10) and it seems a new conflict has occurred with ex-mortis in the new version.

I'm getting weird window behavior when ex-mortis session restore is enabled (where non took place in 3.26). 

Typical gedit behavior is to load new text files as new tabs in the same window. If no window was open, exmortis behavior was to open old session and the text file I clicked in nautilus within the same window. Post 3.30, opening my first text file results in ex-mortis creating it's window with the tabs from the session before but the file I clicked will open in a seperate window. This lone behavior would only apply to the first file clicked before gedit's launch. Any subsequent files that I click on nautilus would end up in the correct window (the one with the old session). This behavior goes away if I disable session restore (still works with exmortis close tab undo functionality).

Thanks for your help and thank you again for this awesome extension.

**Comment by jefferyto** [comment]
Thanks for filing this issue - I've noticed similar behaviour recently. I'll try to take a closer look when I have time but I can't make any promises.

**Comment by jefferyto** [comment]
Thanks again for reporting this - just released a new version (0.2.0) that should be a bit smarter about windows when starting up.
