### ISSUE TITLE
No attribute 'append_menu_item' with gedit 3.30.2

### ISSUE THREAD

**Issue by jpfleury** [jefferyto/gedit-ex-mortis#5]
After enabling Ex-Mortis on gedit 3.30.2 on Xubuntu 18.10, I see this error in the terminal:

~~~
Traceback (most recent call last):
  File "/home/moi/.local/share/gedit/plugins/ex-mortis/__init__.py", line 108, in do_activate
    menu_ext.append_menu_item(menu_item)
AttributeError: 'NoneType' object has no attribute 'append_menu_item'
~~~
 I'm still able to access the Preferences window and check "Restore windows between sessions", but it doesn't work.

**Comment by jefferyto** [comment]
Thanks for filing this - this is the plugin trying to add a menu item to the app menu, when there is no app menu :joy:

Will try to find some time to fix this in the next week or so.

**Comment by jefferyto** [comment]
Thanks again for reporting this - hope you can give the new version (0.2.0) a try :smile:
