### ISSUE TITLE
Should this keep unsaved files ?

### ISSUE THREAD

**Issue by stuaxo** [jefferyto/gedit-ex-mortis#8]
I had some text in an unsaved tab, when I quit I expected ex-mortis to restore it on next startup, but it didn''t - is this expected ?

**Comment by jefferyto** [comment]
Sorry about your data loss. In the README under ["Usage"](https://github.com/jefferyto/gedit-ex-mortis#usage) is this:

> Note that only saved files will be reopened. Unsaved files or unsaved changes are not cached in any way. Closed windows with no saved files, i.e. only unsaved or blank documents, will not be reopenable.

When you quit gedit it should have also asked you if you wanted to save your unsaved document.

**Comment by stuaxo** [comment]
Fair enough, I guess I want what might be a different extension, that regularly saves my unsaved documents somewhere so it can restore them on startup - even after a reboot and without explicitly saving.

**Comment by jefferyto** [comment]
You may want to try the new [GNOME Text Editor](https://gitlab.gnome.org/GNOME/gnome-text-editor).

**Comment by stuaxo** [comment]
Oh, fantastic.

That looks good, I'll try or wait for it to arrive in my distro.

Thanks.
